### ISSUE TITLE
IEEEphot instead of IEEEcsmag

### ISSUE THREAD

**Issue by ogencoglu** [DanySK/Template-IEEE-Computer-Society-Magazines#2]
What is the reason for providing the IEEE photonics class in _IEEEcsmag.cls_ even though _IEEEcsmag_ is requested in main tex:

`\ProvidesClass{IEEEphot}[2009/06/23 V1.2]`

**Comment by DanySK** [comment]
Hi, the file is copied straight from IEEE toolkit, there should be no change w.r.t. the original.
Is it maybe out of date? I could update it.

**Comment by ogencoglu** [comment]
I believe the original still has the same at IEEE toolkit. Thanks for reply.

**Comment by DanySK** [comment]
You are welcome. Let me know if you believe it should get updated.
